### ISSUE TITLE
[lesson 7] The name of layout

### ISSUE THREAD

**Issue by ddy-ddy** [iamshaunjp/sveltekit-tutorial#1]
**Hello author.** 

when I create a file called "__layout.reset.svelte"  in your video and code.
I get a wrong info: "__layout.reset has been removed in favour of named layouts: https://kit.svelte.dev/docs/layouts#named-layouts"

and i try to rename it as "__layout-reset.svelte ". it's work!. i guess the reason is the version of sveltekit.

**Comment by ddy-ddy** [comment]
- my package.json has:
```json
"@sveltejs/kit": "next",
```
- Refer to: [https://kit.svelte.dev/docs/layouts#named-layouts](https://kit.svelte.dev/docs/layouts#named-layouts)
- Naming layout file in this way seems to work.

<img width="287" alt="截屏2022-05-02 下午11 39 05" src="https://user-images.githubusercontent.com/58058861/166263476-ee6b5177-31e4-47db-b0a9-10046259de31.png">

**Comment by lvigerust** [comment]
**Edit:** In case anyone else have this problem, move the `__layout-guides.svelte` to the same directory as the default layout file and it should now work as expected. 

**Original:** I managed to get Named Layouts somewhat working, but the `__layout-guides.svelte` also inherits the layout from `__layout.svelte`. Is there an easy way for the `...@guides.svelte` components to explicitly use the _guides_ layout?

![filestructure](https://user-images.githubusercontent.com/70520878/179572129-35d74e8e-5feb-429f-98b1-9a4f08a70cae.png)
![preview](https://user-images.githubusercontent.com/70520878/179572124-ae62a583-b358-420c-9b87-59dd5403af2b.png)

**Comment by ddy-ddy** [comment]
In fact, you should create a file called `__layout-guides.svelte` at the same level as `__layout.svelte`. Then you can create a file called `__layout@guides.svelte` which inherits the layout from `__layout-guides.svelte`. 

It works for me. If you are interested in it. You can take a look at the website I built with sveltekit.There are examples of using layouts.
- [website](https://www.ddy-ddy.com) 
- [github](https://github.com/ddy-ddy/ddy-website)

You can also take a look at this repositery which is an improved version of the tutorial code.
- [sveltekit-concept-study](https://github.com/ddy-ddy/sveltekit-concept-study)

Finally, what I want to say is that this method seems very inconvenient. I dit it according to the [sveltekit document](https://kit.svelte.dev/docs/layouts#named-layouts-scoping). And I don't know if I did it correct. If I'm doing it wrong, or if there is a more convenient way, hopefully you can point it out.

![image](https://user-images.githubusercontent.com/58058861/179651681-9beaf92d-12eb-4368-964f-c4dfa76cda1d.jpeg)
